title: chansuke's blog
description: >
  My notable things about rust, games and so on.
baseurl: '/blog'
url: 'https://chansuke.github.io'
logo: 'https://www.rust-lang.org/logos/rust-logo-64x64-blk.png' # This one is used as blog logo
twitter_username: chansuke_ # Your twitter handle
github_username: chansuke # Your github handle

# Build settings
highlighter: rouge

root: 'https://check-out-my-awesome-blog.org' # Not really sure this is useful, need to cross check with blog writers :)
